# ⚽ 2026 FIFA World Cup: Full Match-by-Match Breakdown
### End-to-End Simulation of All 104 Matches

This notebook provides a granular simulation of the entire 2026 World Cup tournament. 

**Methodology:**
1. **Roster Accuracy:** Using active 2026 squads (recent retirements like Griezmann removed).
2. **Stochastic Scoring:** Scores generated via Poisson distribution based on win probabilities.
3. **Dynamic Narratives:** Every single match from Group A to the Final is simulated with specific scorers and times.

In [1]:
import pandas as pd
import numpy as np
import pickle
import os
import sys
from IPython.display import display, HTML

sys.path.append('../src')
from simulation_engine import run_simulation
from granular_engine import simulate_match_detail

# Setup
with open('../models/high_signal_gb.pkl', 'rb') as f:
    model = pickle.load(f)
rankings = pd.read_csv('../data/fifa_ranking_live.csv')
if 'total_points' not in rankings.columns: rankings = rankings.rename(columns={'points': 'total_points'})
results = pd.read_csv('../data/processed/results_2026_cycle.csv')
squad_ratings = pd.read_csv('../data/processed/squad_ratings.csv')
squad_dict = dict(zip(squad_ratings['team'], squad_ratings['squad_rating']))
rankings['date'] = pd.to_datetime('2026-05-25')
results['date'] = pd.to_datetime(results['date'])
wc_start = pd.to_datetime('2026-06-11')

print("Environment Ready.")

Environment Ready.

## 1. Group Stage Simulation (72 Matches)
Simulating every match in Groups A through L.

In [2]:
groups = {
    'A': ['Algeria', 'Argentina', 'Austria', 'Jordan'],
    'B': ['Australia', 'Paraguay', 'Turkey', 'United States'],
    'C': ['Belgium', 'Egypt', 'IR Iran', 'New Zealand'],
    'D': ['Bosnia and Herzegovina', 'Canada', 'Qatar', 'Switzerland'],
    'E': ['Brazil', 'Haiti', 'Morocco', 'Scotland'],
    'F': ['Cabo Verde', 'Saudi Arabia', 'Spain', 'Uruguay'],
    'G': ['Colombia', 'Congo DR', 'Portugal', 'Uzbekistan'],
    'H': ['Croatia', 'England', 'Ghana', 'Panama'],
    'I': ['Curaçao', 'Ecuador', 'Germany', "Côte d'Ivoire"],
    'J': ['Czechia', 'Mexico', 'South Africa', 'Korea Republic'],
    'K': ['France', 'Iraq', 'Norway', 'Senegal'],
    'L': ['Japan', 'Netherlands', 'Sweden', 'Tunisia']
}

full_group_results = []
for g_label, teams in groups.items():
    print(f"\n--- Group {g_label} ---")
    matches = []
    for i in range(len(teams)):
        for j in range(i + 1, len(teams)):
            res = simulate_match_detail(teams[i], teams[j], model, rankings, results, squad_dict, wc_start)
            matches.append(res)
    display(pd.DataFrame(matches))
    full_group_results.extend(matches)

--- Group A ---

,Match,Win Prob,Score,Scorers,Winner
0,Algeria vs Argentina,0.33,1 - 0,Algeria: Midfielder (66') | Argentina:,Algeria
1,Algeria vs Austria,0.71,3 - 2,"Algeria: Squad Member (10'), Attacker (84'), A...",Algeria
2,Algeria vs Jordan,0.81,0 - 1,Algeria: | Jordan: Defender (54'),Jordan
3,Argentina vs Austria,0.85,5 - 1,"Argentina: L. Messi (48'), L. Messi (10'), A. ...",Argentina
4,Argentina vs Jordan,0.94,3 - 0,"Argentina: L. Martínez (4'), L. Messi (28'), L...",Argentina
5,Austria vs Jordan,0.70,2 - 3,"Austria: Squad Member (87'), Squad Member (50'...",Jordan

--- Group B ---

,Match,Win Prob,Score,Scorers,Winner
0,Australia vs Paraguay,0.48,0 - 2,"Australia: | Paraguay: Squad Member (86'), Mi...",Paraguay
1,Australia vs Turkey,0.41,2 - 2,"Australia: Midfielder (59'), Attacker (9') | T...",Turkey
2,Australia vs United States,0.41,1 - 2,Australia: Squad Member (39') | United States:...,United States
3,Paraguay vs Turkey,0.41,0 - 1,Paraguay: | Turkey: Squad Member (65'),Turkey
4,Paraguay vs United States,0.41,1 - 1,Paraguay: Attacker (21') | United States: Midf...,United States
5,Turkey vs United States,0.49,0 - 4,"Turkey: | United States: Squad Member (38'), ...",United States

--- Group C ---

,Match,Win Prob,Score,Scorers,Winner
0,Belgium vs Egypt,0.72,0 - 0,Belgium: | Egypt:,Egypt
1,Belgium vs IR Iran,0.87,4 - 1,"Belgium: L. Trossard (48'), R. Lukaku (59'), R...",Belgium
2,Belgium vs New Zealand,0.93,4 - 0,"Belgium: R. Lukaku (59'), Loïs Openda (71'), J...",Belgium
3,Egypt vs IR Iran,0.67,1 - 1,Egypt: Attacker (81') | IR Iran: Midfielder (19'),IR Iran
4,Egypt vs New Zealand,0.81,1 - 1,Egypt: Squad Member (12') | New Zealand: Midfi...,New Zealand
5,IR Iran vs New Zealand,0.67,1 - 1,IR Iran: Squad Member (89') | New Zealand: Mid...,New Zealand

--- Group D ---

,Match,Win Prob,Score,Scorers,Winner
0,Bosnia and Herzegovina vs Canada,0.72,2 - 1,"Bosnia and Herzegovina: Squad Member (89'), Sq...",Bosnia and Herzegovina
1,Bosnia and Herzegovina vs Qatar,0.77,1 - 0,Bosnia and Herzegovina: Attacker (75') | Qatar:,Bosnia and Herzegovina
2,Bosnia and Herzegovina vs Switzerland,0.41,0 - 2,Bosnia and Herzegovina: | Switzerland: Attack...,Switzerland
3,Canada vs Qatar,0.55,2 - 1,"Canada: T. Buchanan (4'), C. Larin (24') | Qat...",Canada
4,Canada vs Switzerland,0.25,0 - 0,Canada: | Switzerland:,Switzerland
5,Qatar vs Switzerland,0.11,1 - 1,Qatar: Attacker (28') | Switzerland: Squad Mem...,Switzerland

--- Group E ---

,Match,Win Prob,Score,Scorers,Winner
0,Brazil vs Haiti,0.78,2 - 0,"Brazil: Endrick (28'), Raphinha (45') | Haiti:",Brazil
1,Brazil vs Morocco,0.78,4 - 0,"Brazil: Rodrygo (51'), Rodrygo (25'), Raphinha...",Brazil
2,Brazil vs Scotland,0.71,2 - 3,"Brazil: Endrick (82'), Rodrygo (69') | Scotlan...",Scotland
3,Haiti vs Morocco,0.26,0 - 4,"Haiti: | Morocco: A. El Kaabi (73'), B. Diaz ...",Morocco
4,Haiti vs Scotland,0.19,0 - 6,"Haiti: | Scotland: Defender (34'), Squad Memb...",Scotland
5,Morocco vs Scotland,0.55,2 - 0,"Morocco: A. El Kaabi (77'), A. El Kaabi (18') ...",Morocco

--- Group F ---

,Match,Win Prob,Score,Scorers,Winner
0,Cabo Verde vs Saudi Arabia,0.51,2 - 4,"Cabo Verde: Attacker (53'), Midfielder (37') |...",Saudi Arabia
1,Cabo Verde vs Spain,0.08,0 - 3,"Cabo Verde: | Spain: Alvaro Morata (29'), Dan...",Spain
2,Cabo Verde vs Uruguay,0.12,1 - 4,Cabo Verde: Squad Member (15') | Uruguay: F. P...,Uruguay
3,Saudi Arabia vs Spain,0.06,0 - 6,"Saudi Arabia: | Spain: Nico Williams (61'), D...",Spain
4,Saudi Arabia vs Uruguay,0.11,0 - 4,"Saudi Arabia: | Uruguay: F. Valverde (29'), F...",Uruguay
5,Spain vs Uruguay,0.63,0 - 0,Spain: | Uruguay:,Uruguay

--- Group G ---

,Match,Win Prob,Score,Scorers,Winner
0,Colombia vs Congo DR,0.87,5 - 0,"Colombia: J. Rodríguez (7'), J. Córdoba (19'),...",Colombia
1,Colombia vs Portugal,0.39,2 - 0,"Colombia: J. Córdoba (73'), J. Rodríguez (81')...",Colombia
2,Colombia vs Uzbekistan,0.87,2 - 0,"Colombia: J. Rodríguez (80'), J. Rodríguez (45...",Colombia
3,Congo DR vs Portugal,0.16,0 - 3,"Congo DR: | Portugal: C. Ronaldo (39'), Gonça...",Portugal
4,Congo DR vs Uzbekistan,0.52,0 - 1,Congo DR: | Uzbekistan: Squad Member (83'),Uzbekistan
5,Portugal vs Uzbekistan,0.84,2 - 1,"Portugal: C. Ronaldo (12'), C. Ronaldo (75') |...",Portugal

--- Group H ---

,Match,Win Prob,Score,Scorers,Winner
0,Croatia vs England,0.42,3 - 2,"Croatia: Squad Member (18'), Midfielder (74'),...",Croatia
1,Croatia vs Ghana,0.88,2 - 0,"Croatia: Squad Member (56'), Squad Member (51'...",Croatia
2,Croatia vs Panama,0.86,1 - 0,Croatia: Defender (7') | Panama:,Croatia
3,England vs Ghana,0.84,1 - 0,England: H. Kane (50') | Ghana:,England
4,England vs Panama,0.81,1 - 0,England: P. Foden (39') | Panama:,England
5,Ghana vs Panama,0.43,2 - 2,"Ghana: Squad Member (78'), Midfielder (4') | P...",Panama

--- Group I ---

,Match,Win Prob,Score,Scorers,Winner
0,Curaçao vs Ecuador,0.17,0 - 1,Curaçao: | Ecuador: Midfielder (83'),Ecuador
1,Curaçao vs Germany,0.04,0 - 3,"Curaçao: | Germany: N. Füllkrug (88'), F. Wir...",Germany
2,Curaçao vs Côte d'Ivoire,0.13,0 - 3,"Curaçao: | Côte d'Ivoire: Squad Member (15'),...",Côte d'Ivoire
3,Ecuador vs Germany,0.41,0 - 1,Ecuador: | Germany: J. Musiala (63'),Germany
4,Ecuador vs Côte d'Ivoire,0.44,2 - 2,"Ecuador: Attacker (49'), Attacker (59') | Côte...",Côte d'Ivoire
5,Germany vs Côte d'Ivoire,0.57,1 - 2,Germany: K. Havertz (20') | Côte d'Ivoire: Mid...,Côte d'Ivoire

--- Group J ---

,Match,Win Prob,Score,Scorers,Winner
0,Czechia vs Mexico,0.27,0 - 3,"Czechia: | Mexico: S. Giménez (82'), S. Gimén...",Mexico
1,Czechia vs South Africa,0.66,0 - 0,Czechia: | South Africa:,South Africa
2,Czechia vs Korea Republic,0.49,1 - 0,Czechia: Midfielder (56') | Korea Republic:,Czechia
3,Mexico vs South Africa,0.81,2 - 1,"Mexico: H. Martín (20'), J. Quiñones (27') | S...",Mexico
4,Mexico vs Korea Republic,0.73,2 - 1,"Mexico: E. Álvarez (86'), H. Martín (10') | Ko...",Mexico
5,South Africa vs Korea Republic,0.37,0 - 4,South Africa: | Korea Republic: Squad Member ...,Korea Republic

--- Group K ---

,Match,Win Prob,Score,Scorers,Winner
0,France vs Iraq,0.81,2 - 0,"France: M. Thuram (57'), R. Kolo Muani (10') |...",France
1,France vs Norway,0.84,2 - 1,"France: K. Mbappé (72'), K. Mbappé (39') | Nor...",France
2,France vs Senegal,0.75,4 - 1,"France: O. Dembélé (41'), R. Kolo Muani (2'), ...",France
3,Iraq vs Norway,0.31,3 - 3,"Iraq: Midfielder (84'), Attacker (53'), Squad ...",Norway
4,Iraq vs Senegal,0.33,0 - 0,Iraq: | Senegal:,Senegal
5,Norway vs Senegal,0.45,0 - 1,Norway: | Senegal: Squad Member (23'),Senegal

--- Group L ---

,Match,Win Prob,Score,Scorers,Winner
0,Japan vs Netherlands,0.26,3 - 3,"Japan: A. Ueda (44'), A. Ueda (81'), T. Kubo (...",Netherlands
1,Japan vs Sweden,0.24,0 - 5,"Japan: | Sweden: Midfielder (41'), Midfielder...",Sweden
2,Japan vs Tunisia,0.49,2 - 3,"Japan: K. Mitoma (44'), A. Ueda (80') | Tunisi...",Tunisia
3,Netherlands vs Sweden,0.57,3 - 2,"Netherlands: Xavi Simons (67'), Memphis Depay ...",Netherlands
4,Netherlands vs Tunisia,0.86,0 - 0,Netherlands: | Tunisia:,Tunisia
5,Sweden vs Tunisia,0.74,6 - 0,"Sweden: Attacker (20'), Midfielder (10'), Atta...",Sweden

## 2. Knockout Phase (32 matches)
From the Round of 32 to the Grand Final.

In [3]:
# Get bracket structure from the professional simulation
_, _, knockout_data = run_simulation()

final_ko_breakdown = []
for match in knockout_data:
    stage = match['Round']
    h, a = match['Matchup']
    detailed_res = simulate_match_detail(h, a, model, rankings, results, squad_dict, wc_start + pd.Timedelta(days=25), is_ko=True)
    detailed_res['Stage'] = stage
    final_ko_breakdown.append(detailed_res)

print("\n--- Complete Knockout Stage Breakdown ---")
ko_df = pd.DataFrame(final_ko_breakdown)
display(ko_df[['Stage', 'Match', 'Score', 'Win Prob', 'Scorers']])

--- Complete Knockout Stage Breakdown ---

,Stage,Match,Score,Win Prob,Scorers
0,R32,Argentina vs Korea Republic,5 - 0,0.89,"Argentina: E. Fernández (48'), E. Fernández (6..."
1,R32,United States vs Norway,0 - 1,0.50,United States: | Norway: Defender (9')
2,R32,Belgium vs Ecuador,3 - 0,0.59,"Belgium: L. Trossard (21'), K. De Bruyne (87')..."
3,R32,Switzerland vs Scotland,1 - 0,0.51,Switzerland: Attacker (24') | Scotland:
4,R32,Brazil vs Austria,2 - 0,0.84,"Brazil: Bruno Guimarães (24'), Vinícius Jr. (4..."
5,R32,Spain vs IR Iran,3 - 0,0.91,"Spain: L. Yamal (7'), L. Yamal (29'), Dani Olm..."
6,R32,Portugal vs Canada,2 - 0,0.85,"Portugal: C. Ronaldo (10'), Bruno Fernandes (6..."
7,R32,England vs Panama,0 - 1,0.74,England: | Panama: Squad Member (21')
8,R32,Germany vs Algeria,2 - 1,0.72,"Germany: K. Havertz (78'), N. Füllkrug (33') |..."
9,R32,Mexico vs Turkey,2 - 1,0.70,"Mexico: H. Martín (46'), S. Giménez (87') | Tu..."
10,R32,France vs Egypt,2 - 1,0.76,"France: O. Dembélé (3'), R. Kolo Muani (24') |..."
11,R32,Netherlands vs Bosnia and Herzegovina,6 - 0,0.74,"Netherlands: T. Koopmeiners (89'), C. Gakpo (8..."
12,R32,Morocco vs Uruguay,2 - 5,0.32,"Morocco: A. Hakimi (55'), B. Diaz (8') | Urugu..."
13,R32,Colombia vs Croatia,1 - 0,0.41,Colombia: J. Rodríguez (42') | Croatia:
14,R32,Côte d'Ivoire vs Czechia,3 - 0,0.71,"Côte d'Ivoire: Squad Member (12'), Squad Membe..."
15,R32,Senegal vs Sweden,1 - 4,0.28,Senegal: Attacker (45') | Sweden: Midfielder (...
16,Round of 16,Argentina vs Norway,6 - 0,0.89,"Argentina: L. Messi (20'), E. Fernández (5'), ..."
17,Round of 16,Belgium vs Switzerland,2 - 1,0.62,"Belgium: K. De Bruyne (31'), K. De Bruyne (21'..."
18,Round of 16,Brazil vs Spain,3 - 2,0.45,"Brazil: Raphinha (39'), Rodrygo (28'), Gabriel..."
19,Round of 16,Portugal vs England,2 - 3,0.37,"Portugal: Bruno Fernandes (40'), C. Ronaldo (8..."
20,Round of 16,Germany vs Mexico,3 - 4,0.58,"Germany: N. Füllkrug (39'), L. Sané (29'), J. ..."
21,Round of 16,France vs Netherlands,4 - 0,0.64,"France: K. Mbappé (45'), K. Mbappé (18'), B. B..."
22,Round of 16,Uruguay vs Croatia,1 - 2,0.42,Uruguay: F. Valverde (58') | Croatia: Squad Me...
23,Round of 16,Côte d'Ivoire vs Sweden,3 - 1,0.55,"Côte d'Ivoire: Squad Member (37'), Defender (6..."
24,Quarter-finals,Argentina vs Belgium,1 - 0,0.58,Argentina: J. Álvarez (6') | Belgium:
25,Quarter-finals,Spain vs England,0 - 2,0.38,"Spain: | England: J. Bellingham (45'), C. Pal..."
26,Quarter-finals,Germany vs France,0 - 1,0.31,Germany: | France: K. Mbappé (39')
27,Quarter-finals,Croatia vs Côte d'Ivoire,2 - 1,0.55,"Croatia: Attacker (29'), Defender (75') | Côte..."
28,Semi-finals,Argentina vs England,2 - 1,0.36,"Argentina: J. Álvarez (2'), L. Messi (57') | E..."
29,Semi-finals,France vs Croatia,0 - 1,0.61,France: | Croatia: Squad Member (16')
30,Final,England vs France,1 - 2,0.56,England: O. Watkins (28') | France: K. Mbappé ...

## 3. Final Result Summary

In [4]:
champion_res = final_ko_breakdown[-1]
print(f"🥇 2026 WORLD CUP WINNER: {champion_res['Winner'].upper()}")
print(f"Final Match: {champion_res['Match']}")
print(f"Final Score: {champion_res['Score']}")
print(f"The Deciding Goals: {champion_res['Scorers']}")

🥇 2026 WORLD CUP WINNER: FRANCE
Final Match: England vs France
Final Score: 1 - 2
The Deciding Goals: England: O. Watkins (28') | France: K. Mbappé (81'), K. Mbappé (68')